# Generated by Django 4.0.1 on 2022-01-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlShortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('short_url', models.CharField(blank=True, default='', max_length=15, unique=True)),
                ('long_url', models.URLField(blank=True, default='', null=True)),
                ('click_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
