# Generated by Django 4.0.1 on 2022-01-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_app', '0004_alter_urlshortener_click_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='urlshortener',
            name='long_url',
            field=models.URLField(default=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='urlshortener',
            name='short_url',
            field=models.CharField(max_length=15),
        ),
    ]
